site_name: fc-audit Documentation
site_description: Documentation for the fc-audit FreeCAD document analysis tool
site_author: Roy Wright
repo_url: https://github.com/royw/fc-audit
repo_name: royw/fc-audit

theme:
  name: material
  features:
    - navigation.instant
    - navigation.tracking
    - navigation.sections
    - navigation.expand
    - navigation.indexes
    - toc.follow
    - search.suggest
    - search.highlight
    - content.tabs.link
    - content.code.annotation
    - content.code.copy
  palette:
    - scheme: default
      toggle:
        icon: material/brightness-7
        name: Switch to dark mode
    - scheme: slate
      toggle:
        icon: material/brightness-4
        name: Switch to light mode
  icon:
    repo: fontawesome/brands/github

plugins:
  - search
  - autorefs
  - mkdocstrings:
      default_handler: python
      handlers:
        python:
          paths: [src]
          options:
            docstring_style: google
            show_source: true
            show_root_heading: true
            show_root_full_path: true
            show_if_no_docstring: true
            heading_level: 2

markdown_extensions:
  - pymdownx.highlight:
      anchor_linenums: true
      line_spans: __span
      pygments_lang_class: true
  - pymdownx.inlinehilite
  - pymdownx.snippets
  - pymdownx.superfences
  - admonition
  - pymdownx.details
  - pymdownx.tabbed:
      alternate_style: true
  - tables
  - toc:
      permalink: true

nav:
  - Home: index.md
  - API Reference:
    - CLI: reference/cli.md
    - FreeCAD Document: reference/fcstd.md
    - Parser: reference/parser.md
    - Alias Output: reference/alias_outputter.md
    - Properties Output: reference/properties_outputter.md
    - Reference Collection: reference/reference_collector.md
    - Reference Output: reference/reference_outputter.md
    - Validation: reference/validation.md
    - Logging: reference/logging.md
    - Exceptions: reference/exceptions.md
